name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: apt update
      run:  sudo apt-get update
    - name: install tooling
      run: sudo apt-get install -y build-essential valgrind libc6-dbg clang-tidy bear
    - name: make
      run: make bear
    - name: lint, test, and valgrind
      run: make check
